const images = [
  {
    id: 1,
    description: 'Кредиты на любой случай',
    buttonText: 'Рассчитать кредит',
    buttonLink: '/test',
    imgDesktopWebp: '/assets/slider/big/2x/slide-1.desktop.2x.webp',
    imgDesktopJpg: '/assets/slider/big/2x/slide-1.desktop.2x.jpg',
    imgTabletWebp: '/assets/slider/middle/2x/slide-1.tablet.webp',
    imgTabletJpg: '/assets/slider/middle/2x/slide-1.tablet.jpg',
    imgMobileWebp: '/assets/slider/small/2x/slide-1.mobile.2x.webp',
    imgMobileJpg: '/assets/slider/small/2x/slide-1.mobile.2x.jpg',
  },
  {
    id: 2,
    description: 'Ваша уверенность в завтрашнем дне',
    imgDesktopWebp: '/assets/slider/big/2x/slide-2.desktop.2x.webp',
    imgDesktopJpg: '/assets/slider/big/2x/slide-2.desktop.2x.jpg',
    imgTabletWebp: '/assets/slider/middle/2x/slide-2.tablet.webp',
    imgTabletJpg: '/assets/slider/middle/2x/slide-2.tablet.jpg',
    imgMobileWebp: '/assets/slider/small/2x/slide-2.mobile.2x.webp',
    imgMobileJpg: '/assets/slider/small/2x/slide-2.mobile.2x.jpg',
  },
  {
    id: 3,
    description: 'Всегда рядом',
    buttonText: 'Найти отделение',
    buttonLink: '/test',
    imgDesktopWebp: '/assets/slider/big/2x/slide-3.desktop.2x.webp',
    imgDesktopJpg: '/assets/slider/big/2x/slide-3.desktop.2x.jpg',
    imgTabletWebp: '/assets/slider/middle/2x/slide-3.tablet.webp',
    imgTabletJpg: '/assets/slider/middle/2x/slide-3.tablet.webp',
    imgMobileWebp: '/assets/slider/small/2x/slide-3.mobile.2x.webp',
    imgMobileJpg: '/assets/slider/small/2x/slide-3.mobile.2x.jpg',
  },
];
export default images;
