const offersList = [
  {
    id: 0,
    itemButton: 'Вклады',
    itemButtonIcon: '/assets/offers/offer-1-icon.svg',
    title: 'Вклады Лига Банка – это выгодная инвестиция в свое будущее',
    descriptionList: [
      'Проценты по вкладам до 7%',
      'Разнообразные условия',
      'Возможность ежемесячной капитализации или вывод процентов на банковскую карту',
    ],
    buttonText: 'Узнать подробнее',
    buttonLink: '/test',
    imgDesktopWebp: '/assets/offers/big/offer-1.webp',
    imgDesktopJpg: '/assets/offers/big/offer-1.jpg',
    imgTabletWebp: '/assets/offers/middle/offer-1.webp',
    imgTabletJpg: '/assets/offers/middle/offer-1.jpg',
    imgMobileWebp: '/assets/offers/small/offer-1.webp',
    imgMobileJpg: '/assets/offers/small/offer-1.jpg',
  },
  {
    id: 1,
    itemButton: 'Кредиты',
    itemButtonIcon: '/assets/offers/offer-2-icon.svg',
    title: 'Лига Банк выдает кредиты под любые цели',
    descriptionList: [
      'Ипотечный кредит',
      'Автокредит',
      'Потребительский кредит',
    ],
    aditionalText:
      'Рассчитайте ежемесячный платежи ставку по кредиту воспользовавшись нашим кредитным калькулятором',
    imgDesktopWebp: '/assets/offers/big/offer-2.webp',
    imgDesktopJpg: '/assets/offers/big/offer-2.jpg',
    imgTabletWebp: '/assets/offers/middle/offer-2.webp',
    imgTabletJpg: '/assets/offers/middle/offer-2.jpg',
    imgMobileWebp: '/assets/offers/small/offer-2.webp',
    imgMobileJpg: '/assets/offers/small/offer-2.jpg',
  },
  {
    id: 2,
    itemButton: 'Страхование',
    itemButtonIcon: '/assets/offers/offer-3-icon.svg',
    title: 'Лига Страхование — застрахуем все что захотите',
    descriptionList: [
      'Автомобильное страхование',
      'Страхование жизни и здоровья',
      'Страхование недвижимости',
    ],
    buttonText: 'Узнать подробнее',
    buttonLink: '/test',
    imgDesktopWebp: '/assets/offers/big/offer-3.webp',
    imgDesktopJpg: '/assets/offers/big/offer-3.jpg',
    imgTabletWebp: '/assets/offers/middle/offer-3.webp',
    imgTabletJpg: '/assets/offers/middle/offer-3.jpg',
    imgMobileWebp: '/assets/offers/small/offer-3.webp',
    imgMobileJpg: '/assets/offers/small/offer-3.jpg',
  },
  {
    id: 3,
    itemButton: 'Онлайн-сервисы',
    itemButtonIcon: '/assets/offers/offer-4-icon.svg',
    title:
      'Лига Банк — это огромное количество онлайн-сервисов для вашего удобства',
    descriptionList: [
      'Мобильный банк,который всегда под рукой',
      'Приложение Лига-проездной позволит вам оплачивать билеты по всему миру',
      'Узнать подробнее',
    ],
    buttonText: 'Узнать подробнее',
    buttonLink: '/test',
    imgDesktopWebp: '/assets/offers/big/offer-4.webp',
    imgDesktopJpg: '/assets/offers/big/offer-4.jpg',
    imgTabletWebp: '/assets/offers/middle/offer-4.webp',
    imgTabletJpg: '/assets/offers/middle/offer-4.jpg',
    imgMobileWebp: '/assets/offers/small/offer-4.webp',
    imgMobileJpg: '/assets/offers/small/offer-4.jpg',
  },
];

export default offersList;
